//! Generates coalesced Unicode property interval tables at crate-build
//! time. The output lives at `$OUT_DIR/unicode_properties.rs` and is
//! consumed by `src/pegc/unicode_properties.rs` via `include!`.
//!
//! Six properties are emitted: `L` (alphabetic), `Nd` (numeric),
//! `XID_Start`, `XID_Continue`, `ID_Start`, `ID_Continue`. The `Any`
//! property does not need a table — its membership test is the
//! constant `true` modulo the surrogate gap.
//!
//! `unicode-ident` is a build-dep; the runtime closure does not link
//! it. Walking the full 21-bit code-point space at build time runs
//! once per `cargo build` and produces a few hundred coalesced
//! intervals per property.

use std::env;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::PathBuf;

const SURROGATE_LO: u32 = 0xD800;
const SURROGATE_HI: u32 = 0xDFFF;
const MAX_CODE_POINT: u32 = 0x10FFFF;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR not set"));
    let out_path = out_dir.join("unicode_properties.rs");
    let file = File::create(&out_path).expect("could not create unicode_properties.rs");
    let mut w = BufWriter::new(file);

    writeln!(
        w,
        "// Generated by build.rs. Do not edit. Source: unicode-ident + std::char predicates."
    )
    .unwrap();

    emit_table(&mut w, "L_RANGES", |c| c.is_alphabetic());
    emit_table(&mut w, "ND_RANGES", |c| c.is_numeric());
    emit_table(&mut w, "XID_START_RANGES", unicode_ident::is_xid_start);
    emit_table(
        &mut w,
        "XID_CONTINUE_RANGES",
        unicode_ident::is_xid_continue,
    );
    // ID_Start / ID_Continue reuse XID predicates as today. The XID
    // variants are the spec-recommended identifier definitions; the
    // distinction is a hair's-breadth edge-case set that we don't
    // currently care about.
    emit_table(&mut w, "ID_START_RANGES", unicode_ident::is_xid_start);
    emit_table(&mut w, "ID_CONTINUE_RANGES", unicode_ident::is_xid_continue);
}

fn emit_table<W: Write>(w: &mut W, name: &str, pred: impl Fn(char) -> bool) {
    let ranges = collect_ranges(pred);
    writeln!(w, "pub const {}: &[(u32, u32)] = &[", name).unwrap();
    for (lo, hi) in &ranges {
        writeln!(w, "    (0x{:X}, 0x{:X}),", lo, hi).unwrap();
    }
    writeln!(w, "];").unwrap();
}

fn collect_ranges(pred: impl Fn(char) -> bool) -> Vec<(u32, u32)> {
    let mut ranges: Vec<(u32, u32)> = Vec::new();
    let mut current_start: Option<u32> = None;
    for cp in 0u32..=MAX_CODE_POINT {
        if (SURROGATE_LO..=SURROGATE_HI).contains(&cp) {
            if let Some(start) = current_start.take() {
                ranges.push((start, cp - 1));
            }
            continue;
        }
        let Some(ch) = char::from_u32(cp) else {
            if let Some(start) = current_start.take() {
                ranges.push((start, cp - 1));
            }
            continue;
        };
        if pred(ch) {
            if current_start.is_none() {
                current_start = Some(cp);
            }
        } else if let Some(start) = current_start.take() {
            ranges.push((start, cp - 1));
        }
    }
    if let Some(start) = current_start {
        ranges.push((start, MAX_CODE_POINT));
    }
    ranges
}
