[workspace]
resolver = "2"
members = ["crates/runtime", "crates/compiler", "crates/bin"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.78"
license = "MIT OR Apache-2.0"
authors = ["Stefano Baghino <stefano@baghino.me>"]
repository = "https://github.com/stefanobaghino/syntax-highlighter"
homepage = "https://github.com/stefanobaghino/syntax-highlighter"
