# JSON grammar with highlight annotations.

*trivia     <- \s*

root        <- \s* value \s*

value       <- @string{string}
             / @number{number}
             / object
             / array
             / @constant{'true'}
             / @constant{'false'}
             / @constant{'null'}

object      <- @punctuation{'{'} \s*
               (pair (\s* @punctuation{','} \s* pair)*)?
               \s* @punctuation{'}'}

pair        <- @property{string} \s* @punctuation{':'} \s* value

array       <- @punctuation{'['} \s*
               (value (\s* @punctuation{','} \s* value)*)?
               \s* @punctuation{']'}

string      <- '"' string_char* '"'
string_char <- '\\' ["\\/bfnrt]
             / '\\' 'u' [\da-fA-F]{4}
             / [^"\\]

number      <- '-'? int frac? exp?
int         <- '0' / [1-9] \d*
frac        <- '.' \d+
exp         <- [eE] [+\-]? \d+
